name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/ci.yaml@77762dfec6f9722d1b57acdfe352dcd16a1dc272
    secrets: inherit
